baseURL = 'https://blogtest-2q5.pages.dev'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal'

[params]
  # theme options
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    languageName = "English"
    title = "My Blog"

    [languages.en.params]
      subtitle = "A simple, retro theme for Hugo"

      [languages.en.params.logo]
        logoText = "My Blog"
        logoHomeLink = "/"